#include "app/app.h"
#include "app/enums.h" // Has all the Id's / Enums

#include <furi.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/modules/menu.h>
#include <gui/modules/popup.h>
#include <gui/scene_manager.h>
#include <gui/view_dispatcher.h>

#define TAG "tracker_app"

#include <trackerflipx_icons.h> // created later after ubft run

/** main menu callback - sends a custom event to the scene manager based on the
 * menu selection */
void menu_callback_main_menu(void *context, uint32_t index) {
  FURI_LOG_T(TAG, "menu_callback_main_menu");
  App *app = context;
  switch (index) {
  case AppMenuSelection_One:
    scene_manager_handle_custom_event(app->scene_manager,
                                      AppEvent_ShowPopupOne);
    break;
  case AppMenuSelection_Two:
    scene_manager_handle_custom_event(app->scene_manager,
                                      AppEvent_ShowPopupTwo);
    break;
  }
}

/** resets the menu, gives it content, callbacks and selection enums */
void scene_on_enter_main_menu(void *context) {
  FURI_LOG_T(TAG, "scene_on_enter_main_menu");
  App *app = context;
  menu_reset(app->menu);

  // NB. icons are specified as NULL below, because:
  // * icons are _always_ animated by the menu
  // * the icons provided (&I_one, &I_two) are generated by the build process
  // * these icons do not have a framerate (resulting in a division by zero)
  menu_add_item(app->menu, "Quick continue last task", NULL,
                AppMenuSelection_One, menu_callback_main_menu, app);

  menu_add_item(app->menu, "Create a new task", NULL, AppMenuSelection_One,
                menu_callback_main_menu, app);
  menu_add_item(app->menu, "View tasks", NULL, AppMenuSelection_Two,
                menu_callback_main_menu, app);
  menu_add_item(app->menu, "Show stats", NULL, AppMenuSelection_Two,
                menu_callback_main_menu, app);
  menu_add_item(app->menu, "Exit", NULL, AppMenuSelection_Two,
                menu_callback_main_menu, app);

  view_dispatcher_switch_to_view(app->view_dispatcher, AppView_Menu);
}

/** main menu event handler - switches scene based on the event */
bool scene_on_event_main_menu(void *context, SceneManagerEvent event) {
  FURI_LOG_T(TAG, "scene_on_event_main_menu");
  App *app = context;
  bool consumed = false;
  switch (event.type) {
  case SceneManagerEventTypeCustom:
    switch (event.event) {
    case AppEvent_ShowPopupOne:
      scene_manager_next_scene(app->scene_manager, FirstPopup);
      consumed = true;
      break;
    case AppEvent_ShowPopupTwo:
      scene_manager_next_scene(app->scene_manager, SecondPopup);
      consumed = true;
      break;
    }
    break;
  default: // eg. SceneManagerEventTypeBack, SceneManagerEventTypeTick
    consumed = false;
    break;
  }
  return consumed;
}

void scene_on_exit_main_menu(void *context) {
  FURI_LOG_T(TAG, "scene_on_exit_main_menu");
  App *app = context;
  menu_reset(app->menu);
}

/* popup 1 scene */

void scene_on_enter_popup_one(void *context) {
  FURI_LOG_T(TAG, "scene_on_enter_popup_one");
  App *app = context;
  popup_reset(app->popup);
  popup_set_context(app->popup, app);
  popup_set_header(app->popup, "Popup One", 64, 10, AlignCenter, AlignTop);
  popup_set_icon(app->popup, 10, 10, &I_cvc_36x36);
  popup_set_text(app->popup, "One! One popup. Ah ah ah...", 64, 20, AlignLeft,
                 AlignTop);
  view_dispatcher_switch_to_view(app->view_dispatcher, AppView_Popup);
}

bool scene_on_event_popup_one(void *context, SceneManagerEvent event) {
  FURI_LOG_T(TAG, "scene_on_event_popup_one");
  UNUSED(context);
  UNUSED(event);
  return false; // don't handle any events
}

void scene_on_exit_popup_one(void *context) {
  FURI_LOG_T(TAG, "scene_on_exit_popup_one");
  App *app = context;
  popup_reset(app->popup);
}

/* popup 2 scene */

void scene_on_enter_popup_two(void *context) {
  FURI_LOG_T(TAG, "scene_on_enter_popup_two");
  App *app = context;
  popup_reset(app->popup);
  popup_set_context(app->popup, app);
  popup_set_header(app->popup, "Popup Two", 64, 10, AlignCenter, AlignTop);
  popup_set_icon(app->popup, 10, 10, &I_cvc_36x36);
  popup_set_text(app->popup, "Two! Two popups. (press back)", 64, 20, AlignLeft,
                 AlignTop);
  view_dispatcher_switch_to_view(app->view_dispatcher, AppView_Popup);
}

bool scene_on_event_popup_two(void *context, SceneManagerEvent event) {
  FURI_LOG_T(TAG, "scene_on_event_popup_two");
  UNUSED(context);
  UNUSED(event);
  return false; // don't handle any events
}

void scene_on_exit_popup_two(void *context) {
  FURI_LOG_T(TAG, "scene_on_exit_popup_two");
  App *app = context;
  popup_reset(app->popup);
}

/** collection of all scene on_enter handlers - in the same order as their enum
 */
void (*const scene_on_enter_handlers[])(void *) = {scene_on_enter_main_menu,
                                                   scene_on_enter_popup_one,
                                                   scene_on_enter_popup_two};

/** collection of all scene on event handlers - in the same order as their enum
 */
bool (*const scene_on_event_handlers[])(void *, SceneManagerEvent) = {
    scene_on_event_main_menu, scene_on_event_popup_one,
    scene_on_event_popup_two};

/** collection of all scene on exit handlers - in the same order as their enum
 */
void (*const scene_on_exit_handlers[])(void *) = {
    scene_on_exit_main_menu, scene_on_exit_popup_one, scene_on_exit_popup_two};

/** collection of all on_enter, on_event, on_exit handlers */
const SceneManagerHandlers scene_event_handlers = {
    .on_enter_handlers = scene_on_enter_handlers,
    .on_event_handlers = scene_on_event_handlers,
    .on_exit_handlers = scene_on_exit_handlers,
    .scene_num = Count};

/** custom event handler - passes the event to the scene manager */
bool scene_manager_custom_event_callback(void *context, uint32_t custom_event) {
  FURI_LOG_T(TAG, "scene_manager_custom_event_callback");
  furi_assert(context);
  App *app = context;
  return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

/** navigation event handler - passes the event to the scene manager */
bool scene_manager_navigation_event_callback(void *context) {
  FURI_LOG_T(TAG, "scene_manager_navigation_event_callback");
  furi_assert(context);
  App *app = context;
  return scene_manager_handle_back_event(app->scene_manager);
}

/** initialise the scene manager with all handlers */
void scene_manager_init(App *app) {
  FURI_LOG_T(TAG, "scene_manager_init");
  app->scene_manager = scene_manager_alloc(&scene_event_handlers, app);
}

/** initialise the views, and initialise the view dispatcher with all views */
void view_dispatcher_init(App *app) {
  FURI_LOG_T(TAG, "view_dispatcher_init");
  app->view_dispatcher = view_dispatcher_alloc();
  view_dispatcher_enable_queue(app->view_dispatcher);

  // allocate each view
  FURI_LOG_D(TAG, "view_dispatcher_init allocating views");
  app->menu = menu_alloc();
  app->popup = popup_alloc();

  // assign callback that pass events from views to the scene manager
  FURI_LOG_D(TAG, "view_dispatcher_init setting callbacks");
  view_dispatcher_set_event_callback_context(app->view_dispatcher, app);
  view_dispatcher_set_custom_event_callback(
      app->view_dispatcher, scene_manager_custom_event_callback);
  view_dispatcher_set_navigation_event_callback(
      app->view_dispatcher, scene_manager_navigation_event_callback);

  // add views to the dispatcher, indexed by their enum value
  FURI_LOG_D(TAG, "view_dispatcher_init adding view menu");
  view_dispatcher_add_view(app->view_dispatcher, AppView_Menu,
                           menu_get_view(app->menu));

  FURI_LOG_D(TAG, "view_dispatcher_init adding view popup");
  view_dispatcher_add_view(app->view_dispatcher, AppView_Popup,
                           popup_get_view(app->popup));
}
