#include "../../app.h"
#include "../../enums.h"
#include <furi.h>

#define TAG "tracker_app"

/** main menu callback - sends a custom event to the scene manager based on the
 * menu selection */
void menu_callback_main_menu(void *context, uint32_t index) {
  FURI_LOG_T(TAG, "menu_callback_main_menu");
  App *app = context;
  switch (index) {
  case QuickStart_Menu:
    scene_manager_handle_custom_event(app->scene_manager,
                                      AppEvent_ShowQuickStart);
    break;
  case CreateTask_Menu:
    scene_manager_handle_custom_event(app->scene_manager,
                                      AppEvent_ShowCreateTask);
    break;
  case ViewTasks_Menu:
    scene_manager_handle_custom_event(app->scene_manager,
                                      AppEvent_ShowCreateTask);
    break;
  case ShowStats_Menu:
    scene_manager_handle_custom_event(app->scene_manager, AppEvent_ShowStats);
    break;
  case Exit_Menu:
    scene_manager_handle_back_event(app->scene_manager);
    break;
  }
}

void scene_on_enter_main_menu(void *context) {
  FURI_LOG_T(TAG, "scene_on_enter_main_menu");
  App *app = context;
  menu_reset(app->menu);

  // NB. icons are specified as NULL below, because:
  // * icons are _always_ animated by the menu
  // * the icons provided (&I_one, &I_two) are generated by the build process
  // * these icons do not have a framerate (resulting in a division by zero)
  menu_add_item(app->menu, "Quick continue last task", NULL, QuickStart_Menu,
                menu_callback_main_menu, app);

  menu_add_item(app->menu, "Create a new task", NULL, CreateTask_Menu,
                menu_callback_main_menu, app);
  menu_add_item(app->menu, "View tasks", NULL, ViewTasks_Menu,
                menu_callback_main_menu, app);
  menu_add_item(app->menu, "Show stats", NULL, ShowStats_Menu,
                menu_callback_main_menu, app);
  menu_add_item(app->menu, "Exit", NULL, Exit_Menu, menu_callback_main_menu,
                app);

  view_dispatcher_switch_to_view(app->view_dispatcher, AppView_Menu);
}

/** main menu event handler - switches scene based on the event */
bool scene_on_event_main_menu(void *context, SceneManagerEvent event) {
  FURI_LOG_T(TAG, "scene_on_event_main_menu");
  App *app = context;
  bool consumed = false;
  switch (event.type) {
  case SceneManagerEventTypeCustom:
    switch (event.event) {
    case AppEvent_ShowQuickStart:
      scene_manager_next_scene(app->scene_manager, QuickStart);
      consumed = true;
      break;
    case AppEvent_ShowCreateTask:
      scene_manager_next_scene(app->scene_manager, CreateTask);
      consumed = true;
      break;
    case AppEvent_ShowStats:
      scene_manager_next_scene(app->scene_manager, ShowStats);
      consumed = true;
      break;
    }
    break;

  default: // eg. SceneManagerEventTypeBack, SceneManagerEventTypeTick
    consumed = false;
    break;
  }
  return consumed;
}

void scene_on_exit_main_menu(void *context) {
  FURI_LOG_T(TAG, "scene_on_exit_main_menu");
  App *app = context;
  menu_reset(app->menu);
}